#!/bin/bash

echo "$0: permission denied while reading flags"

if [[ $(id -u) -ne 0 ]]; then
  exit 1
fi

wall "The person on TTY Session $(tty) uses cheese strats!"
sudo pkill -9 -t $(tty | sed 's/^.\{5\}//')
#kill -HUP $$
#kill -9 $PPID
exit 0
